### ISSUE TITLE
Outputing JSON

### ISSUE THREAD

**Issue by RuiAAPeres** [hoedown/hoedown#154]
I was looking at #22. And I saw that hoedown is able to output JSON now, but how do you do it from code? I was able to see @jmendeth [example](https://cloud.githubusercontent.com/assets/1177304/5606914/54a3d99a-9446-11e4-8d88-d1cb57e51452.png), and I searched in wiki, but I couldn't find it. 

I also tested this from the dev branch:

```
→ ./hoedown testing.md --json > out         
Wrong option '--json' found.
```

Thanks

**Comment by jmendeth** [comment]
Hoedown is flexible enough that, instead of using the official renderer that outputs HTML, you could write and use your own renderer. That way, you can get other kinds of output, such as LaTeX or JSON.
In Hoedown's upcoming version (code pushed at `develop` branch), you're even able to work and output any object you want, not only code.

What you see in #22 is a local modification I did to Hoedown to demonstrate that a JSON renderer is possible, but it's only a draft and not present here [yet?].

If you're new to writing renderers, you can start by playing a bit with `html.c` code to get different output, and then use it as a base for a JSON renderer.
