### ISSUE TITLE
hoedown_autolink__www() does not use the flags argument

### ISSUE THREAD

**Issue by marcomaggi** [hoedown/hoedown#162]
I am a new user.  The function ```hoedown_autolink__www()``` does not use the ```flags``` argument and just passes ```0``` to ```check_domain()```, rather than isolate the ```HOEDOWN_AUTOLINK_SHORT_DOMAINS``` flag.  Is this intentional?

**Comment by jmendeth** [comment]
Yeah, it's intentional. `autolink__www` is for detecting `www.something.tld` patterns, thus we need to enforce a dot in the part after `www.`. The `HOEDOWN_AUTOLINK_SHORT_DOMAINS` flag doesn't make sense for this kind of autolinks.

When the whole "short domains" thing [was imported](https://github.com/hoedown/hoedown/commit/11d2add5b43e6c209ca4f7c4f326832f0ba63f70) from Rinku, a `flags` argument was added to all three autolink functions for consistency, in case more flags were added later.
