### ISSUE TITLE
Code block embedded in list affects vertical spacing of future bullets

### ISSUE THREAD

**Issue by joeltine** [hoedown/hoedown#163]
When embedding a code block in a list, it causes the vertical spacing of the bullets below it to be spaced differently. This causes inconsistency in the styling of the page. 

Looking at the generated markup, it looks like it's wrapping `<li>` contents in a `<p>` tag for every list item after the code block. 

Some example markdown that demonstrates the issues:

## TEST CASE                                                                     
                                                                                 
*   Normal bullet                                                                
*   Normal bullet                                                                
*   Increases spacing above and below                                                               
    *   Code snippet                                                                
                                                                                    
        ``` javascript                                                              
        var x = "foo";
        ```                                                                         
                                                                                 
    *   End code snippet
   *    Increased spacing above
*   Increased spacing above and below

**Comment by jmendeth** [comment]
Yeah, this is a known issue. Lists can be either "tight" or "loose". Tight lists only contain a paragraph in their items and have no blank lines between items (it's a bit more complex actually):

     - item 1
     - item 2

     <ul><li>item 1</li><li>item 2</li></ul>

Anything else is a loose list:

    - item 1

      item 1, second paragraph
    - item 2

     <ul><li><p>item 1</p><p>item 1, second paragraph</p></li><li><p>item 2</p></li></ul>

Because a blank line in any item makes the whole list loose, Hoedown cannot know in advance wether a list is loose or tight, it would need to parse all the items, then parse them again and render as appropiate.

So by now it starts parsing/rendering the list items tight (with `is_block == 0`), and when it sees a blank line the rest of the items are rendered loose (thus wrapped in `<p>`).

**Comment by jmendeth** [comment]
The stable version of Hoedown is not developed any more (except for fixes), so I'm closing this issue.

However, please look at the [development version](https://github.com/hoedown/hoedown/tree/develop) which doesn't have this issue.

**Comment by joeltine** [comment]
Thank you! My project is actually using hoextdown (https://github.com/kjdev/hoextdown) an extension to hoedown. Do you know if it would be possible to merge the fix from the development version into hoextdown?

**Comment by jmendeth** [comment]
No, unfortunately, since the development version is a complete rewrite of the current codebase.
It solves this [and many more](https://github.com/hoedown/hoedown/issues/119#issuecomment-61426795) known syntax issues.

However all of the extensions in hoextdown (except meta block and header ID) are already present in the development version, or can be achieved easily by customizing the renderer.

**Comment by uranusjr** [comment]
@joeltine Maybe you can talk to people behind hoextdown, and see whether they are interested in solving this issue. It seems that this exact issue has been reported there (kjdev/hoextdown#3). I think this can be solved without much hassle, but discussions should continue there.

**Comment by jmendeth** [comment]
Agreed. But this one in particular is not too hard to solve, so we could import the fix here.
