### ISSUE TITLE
footnote return link shows up only after first paragraph

### ISSUE THREAD

**Issue by blaenk** [hoedown/hoedown#170]
Not sure if this is already known, but as a heads up so it can be fixed for the rewrite. If I have a footnote that contains more than one paragraph, the 'jump back' link shows up after the first paragraph, not after the entire contents of the footnote body, as I would expect (and as I've observed other markdown processors do, like Pandoc).

**Comment by jmendeth** [comment]
This [seems to be intentional](https://github.com/hoedown/hoedown/blob/master/src/html.c#L519), but I, too, would expect the return link to be at the end. There could have been a renderer option to control this, but you can override the callback anyway.

For the rewrite the link will be at the end, in consistency with Pandoc.

**Comment by blaenk** [comment]
Sweet :) I'll look into overriding the callback for now thanks. Feel free to close this.
