### ISSUE TITLE
Is it possible to fix indentation in fenced code block?

### ISSUE THREAD

**Issue by pacahon** [hoedown/hoedown#172]
Hello, I have a code block:

```
* list item1
* list item 2
* list item 3
  ```python
  def foo(x): # -2 spaces after rendering here
      for i in range(x): # <-- after rendering I got only 2 spaces indentation here (-4 spaces after rendering)
         print("blablabla") # -4 spaces...
      return x #  and so on
  ` `` (intentional whitespace here)
```

And enabled extension `fenced_code`. After rendering I got wrong amount of spaces on `for` statement line (by PEP8 it should be always 4 whitespaces)
It looks like:
```
def foo(x):
  for i in range(x):
      print("blablabla")
  return x
```

GFM works fine in that case. Is it possible to fix this issue?

**Comment by jmendeth** [comment]
This is actually expected behaviour. List items should be indented four spaces, like so:

~~~

  * list item 1
  * list item 2
  * list item 3
    ``` python
    def foo(x): # -2 spaces after rendering here
        for i in range(x): # <-- after rendering I got only 2 spaces indentation here (-4 spaces after rendering)
           print("blablabla") # -4 spaces...
        return x #  and so on
    ```
~~~

If you indent some lines by less than four-spaces (as you did), then the parser "fixes it" by adding two spaces to them. The `for` is already indented enough, so it's not touched. That's why you get that result.

This is a well known issue with the Markdown syntax itself, and it's been addressed in [CommonMark](http://commonmark.org). The next version (in development) of Hoedown supports CommonMark and as such, it will produce what you expect.
