### ISSUE TITLE
Quotation marks in input string causes incorrect output

### ISSUE THREAD

**Issue by njdehoog** [hoedown/hoedown#179]
When using the following input string:

    “This is a quote”\nFollowed by some text

This is the produced HTML output:

    <p>“This is a quote”\nFollowed by some </p>\n

Notice how the word _text_ is missing from the output.

Shouldn't Hoedown be able to handle that input string? Or is this expected behavior?

I'm currently using Hoedown version 3.0.2

**Comment by uranusjr** [comment]
On what OS and shell do you experience this? Are you using the command line utility, or the C API? I suspect this has something to do with your terminal encoding.

**Comment by njdehoog** [comment]
I'm using the C API in this project: https://github.com/njdehoog/swift-hoedown. I'm passing a Swift string directly to the C API.

```swift
public func renderMarkdown(string: String, bufferSize: UInt = 16) -> String? {
    let buffer = hoedown_buffer_new(Int(bufferSize))
    hoedown_document_render(self.internalDocument, buffer, string, string.characters.count);
    
    let htmlOutput = hoedown_buffer_cstr(buffer)
    let output = String.fromCString(htmlOutput)
    
    hoedown_buffer_free(buffer)
    
    return output
}
```

**Comment by njdehoog** [comment]
The Swift documentation suggests that this should be ok:

> A Swift String can be used as a const char* pointer, which will pass the function a pointer to a null-terminated, UTF-8-encoded representation of the string

Explictly creating a C string also doesn't solve the issue:

```swift
 let UTF8String = string.cStringUsingEncoding(NSUTF8StringEncoding)!
 hoedown_document_render(self.internalDocument, buffer, UnsafePointer(UTF8String), string.characters.count);
```

**Comment by uranusjr** [comment]
The problem is `string.charaers.count`. Hoedown takes an array of UTF-8 bytes for input, and the size parameter should specify the size of the array. The Unicode curly quotes, when encoded with UTF-8, take three bytes each:

    “    E2 80 9C
    ”    E2 80 9D

So your input

    “This is a quote”\nFollowed by some text

would be 43 bytes (36 basic characters, one newline character, and two 3-byte characters).

`string.characters.count`, on the other hand, counts how many characters the string logically have. Your string yields 39.

I didn’t test it, but passing `string.utf8.count` instead should solve your problem.

**Comment by jmendeth** [comment]
@uranusjr I was about to begin writing that too... ;-P

**Comment by njdehoog** [comment]
You're right. I totally missed that. Thanks for your help @uranusjr!
