### ISSUE TITLE
Backslash conversion

### ISSUE THREAD

**Issue by pbek** [hoedown/hoedown#200]
Thank you for your wonderful library, I use it in https://github.com/pbek/QOwnNotes.
A user of QOwnNotes posted an issue https://github.com/pbek/QOwnNotes/issues/310 about backslashes:

```
In editor , input \(?0\\d{2}\\) , preview shows (?0\d{2}\) 
input \\(?0\\d{2}\\), preview shows \(?0\\d{2}\)
```

Is there a reason for the conversion?

**Comment by pbek** [comment]
Version 3.0.7 of howdown is used.

**Comment by uranusjr** [comment]
[Babelmark 2 shows identical output across implementations.](http://johnmacfarlane.net/babelmark2/?normalize=1&text=%5C%28%3F0%5C%5Cd%7B2%7D%5C%5C%29%0A%0A%5C%5C%28%3F0%5C%5Cd%7B2%7D%5C%5C%29) Looks like a bug to me.

**Comment by uranusjr** [comment]
Wait. I just built a Hoedown 3.0.7 from scratch, and the result seems correct.

```
$ ./hoedown -v
Built with Hoedown 3.0.7.
$ echo '\(?0\\d{2}\\)' | ./hoedown
<p>(?0\d{2}\)</p>
$ echo '\\(?0\\d{2}\\)' | ./hoedown
<p>\(?0\d{2}\)</p>
```

**Comment by pbek** [comment]
The backslashes stripped off, I don't know if that's a bug of a feature. User wouldn't assume that this will happen...

**Comment by uranusjr** [comment]
[Backslash escaping](https://daringfireball.net/projects/markdown/syntax#backslash) is a feature of Markdown that allows user to input literal characters that have special meanings in Markdown. For example, `*text*` would make text italic, so if you really want `*text*` literally you can type `\*text\*`. The backslashes escape the stars next to them, so they do not act has functional markers.

This causes one side effect: if backslashes escape the next character, how do you actually type a backslash? The answer is you use two backslashes (`\\`) when you want one. The first backslash escape the second one, so that the second one can be used as its literal value.

As you can see in the linked page, `(` is among the escapable characters, so `\(` becomes `(`. And from the above you can see `\\` becomes `\`. These rules account for the stripped backslashes in your examples.

**Comment by pbek** [comment]
That was the missing information: it's for backslash escaping! Thanks a lot!
